// define the constants here
//export const CREATE_GAME = 'CREATE_GAME';
export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const LOAD_COURTS_SUCCESS = 'LOAD_COURTS_SUCCESS';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';

export const FIND_GAMES_SUCCESS = 'FIND_GAMES_SUCCESS';

export const LOAD_LAST_GAME_SUCCESS = 'LOAD_LAST_GAME_SUCCESS';

export const QUICK_JOIN_GAME_SUCCESS = 'QUICK_JOIN_GAME_SUCCESS';

export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';

export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS';

export const CLEAR_PLAYERS_SUCCESS = 'CLEAR_PLAYERS_SUCCESS';
