// games: 
//     initial load: 
export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const LOAD_LAST_GAME_SUCCESS = 'LOAD_LAST_GAME_SUCCESS';
export const LOAD_COURTS_SUCCESS = 'LOAD_COURTS_SUCCESS';
//     actions 
export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const FIND_GAMES_SUCCESS = 'FIND_GAMES_SUCCESS';
export const CLEAR_FOUND_SUCCESS = 'CLEAR_FOUND_SUCCESS';
export const QUICK_JOIN_GAME_SUCCESS = 'QUICK_JOIN_GAME_SUCCESS';
export const CLEAR_PLAYERS_SUCCESS = 'CLEAR_PLAYERS_SUCCESS';


// session: 
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_USER_FRIENDS_SUCCESS = 'GET_USER_FRIENDS_SUCCESS';
export const REMOVE_FROM_FAVORITES_SUCCESS = 'REMOVE_FROM_FAVORITES_SUCCESS';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const LOAD_ALL_MESSAGES_SUCCESS = 'LOAD_ALL_MESSAGES_SUCCESS';


// Profile 
export const GET_PROFILE_USER_SUCCESS = 'GET_PROFILE_USER_SUCCESS'; 
export const GET_PROFILE_FRIENDS_SUCCESS = 'GET_PROFILE_FRIENDS_SUCCESS';
export const SET_IS_CURRENT_USERS_SUCCESS = 'SET_IS_CURRENT_USERS_SUCCESS' ;
export const GET_FRIENDSHIP_STATUS_SUCCESS = 'GET_FRIENDSHIP_STATUS_SUCCESS';
export const UPDATE_FRIENDSHIP_STATUS_SUCCESS = 'UPDATE_FRIENDSHIP_STATUS_SUCCESS';
export const GET_UPCOMING_GAMES_SUCCESS = 'GET_UPCOMING_GAMES_SUCCESS';
export const GET_HISTORY_GAMES_SUCCESS = 'GET_HISTORY_GAMES_SUCCESS';

